name: media_kit_demo
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  crypto: ^3.0.3
  path: ^1.8.3
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5 # For video rendering.
  media_kit_libs_video: ^1.0.5 # Native video dependencies.
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.1.1
  test: ^1.24.0

flutter:
  uses-material-design: true
